version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0  # Version actual utilizada
    commands:
      - echo "Instalando dependencias..."      
      - dotnet restore EmailProcessor/EmailProcessor.csproj
      - dotnet restore MailReader/MailReader.csproj

  build:
    commands:
      - echo "Compilando todos los proyectos..."      
      - dotnet build EmailProcessor/EmailProcessor.csproj --configuration Release
      - dotnet build MailReader/MailReader.csproj --configuration Release

  post_build:
    commands:
      - echo "Publicando y empaquetando EmailProcessor..."
      - dotnet publish EmailProcessor/EmailProcessor.csproj -c Release -o published/EmailProcessor
      
      - echo "Eliminando archivo DatabaseInitializer.runtimeconfig.json..."
      - if (Test-Path "published/EmailProcessor/DatabaseInitializer.runtimeconfig.json") { Remove-Item "published/EmailProcessor/DatabaseInitializer.runtimeconfig.json" }
      
      - echo "Empaquetando EmailProcessor en ZIP usando PowerShell..."
      - Compress-Archive -Path published/EmailProcessor/* -DestinationPath EmailProcessor_ZIP.zip      
      
      - echo "Publicando y empaquetando MailReader..."
      - dotnet publish MailReader/MailReader.csproj -c Release -o published/MailReader
      
      - echo "Empaquetando MailReader en ZIP usando PowerShell..."
      - Compress-Archive -Path published/MailReader/* -DestinationPath MailReader_ZIP.zip

artifacts:
  files:
    - EmailProcessor_ZIP.zip
    - MailReader_ZIP.zip
  discard-paths: yes