version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0  # Version actual utilizada
    commands:
      - echo "Instalando dependencias..."      
      - dotnet restore EmailProcessor/EmailProcessor.csproj
      - dotnet restore MailReader/MailReader.csproj

  build:
    commands:
      - echo "Compilando todos los proyectos..."      
      - dotnet build EmailProcessor/EmailProcessor.csproj --configuration Release
      - dotnet build MailReader/MailReader.csproj --configuration Release

  post_build:
    commands:
      - echo "Publicando y empaquetando EmailProcessor..."
      - dotnet publish EmailProcessor/EmailProcessor.csproj -c Release -o published/EmailProcessor
      
      - echo "Verificando estructura de archivos EmailProcessor antes de empaquetar..."
      - ls -l published/
      - ls -l published/EmailProcessor/
      - cd published/EmailProcessor
      - zip -r ../../EmailProcessor.zip .
      - cd ../..      
      
      - echo "Publicando y empaquetando MailReader..."
      - dotnet publish MailReader/MailReader.csproj -c Release -o published/MailReader
      - echo "Verificando estructura de archivos MailReader antes de empaquetar..."
      - ls -l published/
      - ls -l published/EmailProcessor/

      - cd published/MailReader
      - zip -r ../../MailReader.zip .
      - cd ../..

artifacts:
  files:
    - EmailProcessor.zip
    - MailReader.zip
  discard-paths: yes